Resources:
  ContentReadRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ContentReadRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole

        