Resources:
  ContentReadPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName:
        'Fn::Join':
          - '_'
          - - "ContentReadPolicy"
            - ${self:provider.region}
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: # Gives permission to DynamoDB tables in a specific region
              - dynamodb:Query
              - dynamodb:GetItem
            Resource: 
              "Fn::GetAtt": [ ContentTable, Arn ]
      Roles:
        - 
          Ref: ContentReadRole
          