Resources:
  LoggingPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName:
        'Fn::Join':
          - '_'
          - - "LoggingPolicy"
            - ${self:provider.region}
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource:
              - 'Fn::Join':
                - ':'
                -
                  - 'arn:aws:logs'
                  - Ref: 'AWS::Region'
                  - Ref: 'AWS::AccountId'
                  - 'log-group:/aws/lambda/*:*'
      Roles:
        -
          Ref: ResultReadRole
