Resources:
  userPoolUsers:
    Type: "AWS::Cognito::UserPool"
    Properties:
      MfaConfiguration: OFF
      UserPoolName: user-pool-users-${self:provider.stage}
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: True
          RequireNumbers: True
          RequireSymbols: True
          RequireUppercase: True
      Schema:
        - AttributeDataType: String
          Mutable: false
          Name: "userID"
          Required: false
        - Name: name
          Required: false
        - Name: family_name
          Required: false
  userPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties:
      ClientName: user-pool-client-${self:provider.stage}
      GenerateSecret: false
      UserPoolId:
        Ref: userPoolUsers

Outputs:
  UserPoolUsers:
    Value:
      Fn::GetAtt: userPoolUsers.Arn
    Export:
      Name: user-pool-users-${self:provider.stage}
