Resources:
  ResultTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.result-table}
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
        - AttributeName: result
          AttributeType: N
      KeySchema:
        - AttributeName: email
          KeyType: HASH
        - AttributeName: result
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
